_target_: trl.SFTConfig
output_dir: "smolvlm-instruct-trl-sft-ChartQA"
num_train_epochs: 10
per_device_train_batch_size: 16
gradient_accumulation_steps: 2
warmup_steps: 50
learning_rate: 5e-5
weight_decay: 0.01
logging_steps: 20
save_strategy: "steps"
save_steps: 250
save_total_limit: 2
optim: "adamw_torch_fused"
bf16: true
push_to_hub: false
report_to: ["trackio"]
max_length: null
gradient_checkpointing: false
dataloader_num_workers: 4